using DaemonEngine.OpenGL.DllImport;

namespace DaemonEngine.Graphics.OpenGL.DllImport.Enums;

public enum GLFramebufferStatus : uint
{
    Complete = GLConstants.GL_FRAMEBUFFER_COMPLETE,
    GL_FRAMEBUFFER_UNDEFINED = GLConstants.GL_FRAMEBUFFER_UNDEFINED,
    Unsupported = GLConstants.GL_FRAMEBUFFER_UNSUPPORTED,
	GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT = GLConstants.GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT,
    GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE = GLConstants.GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE,
    GL_FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER = GLConstants.GL_FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER,
	GL_FRAMEBUFFER_INCOMPLETE_READ_BUFFER = GLConstants.GL_FRAMEBUFFER_INCOMPLETE_READ_BUFFER,
	GL_FRAMEBUFFER_INCOMPLETE_LAYER_TARGETS = GLConstants.GL_FRAMEBUFFER_INCOMPLETE_LAYER_TARGETS,
	GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT = GLConstants.GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT
}
